import type { Metadata } from "next";
import { Barlow, Barlow_Condensed, Bellefair } from "next/font/google";
import "./globals.css";

const barlow = Barlow({ subsets: ["latin"], weight: ["400"] });
const barlow_condensed = Barlow_Condensed({ subsets: ["latin"], weight: ["400"] });
const bellefair = Bellefair({ subsets: ["latin"], weight: ["400"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[barlow.className, barlow_condensed.className, bellefair.className].toString()} >{children}</body>
    </html>
  );
}
